[package]
name = "catchub"
version = "0.1.0"
authors = ["Leonard Dahlmann <leo.dahlmann@gmail.com>"]
edition = "2018"

[dependencies]
quicksilver = { version = "=0.4.0-alpha0.2", features = ["stdweb"] }
stdweb = "0.4"
